name: semgrep-sast-scan
on:
  pull_request:
    
jobs:
  semgrep-full-scan:
    runs-on: ubuntu-latest
    permissions: 
     pull-requests: read
     contents: read

    steps:
      - name: Fetch target repository
        uses: actions/checkout@v2

      - name: Fetch Automation Scripts
        uses: actions/checkout@v2
        with:
          repository: Red-Assassin-Org/ci-cd-private
          path: automation-scripts

      - name: list directory structure
        run: ls -la
      - name: Setup Semgrep
        run: |
          bash -i automation-scripts/scripts/setup-semgrep.sh

      - name: Run built-in semgrep rules
        env: 
          PR_NUMBER: ${{ github.event.number }}
          GH_TOKEN: ${{ github.token }}
        run: | 
          if [ $GITHUB_EVENT_NAME == "pull_request" ]
          then
            gh pr view $PR_NUMBER --json files --jq '.files.[].path' | tee scan-files-list.txt
            cat scan-files-list.txt | xargs -P 5 -I {} semgrep --config "p/sql-injection" {} -q
          else
            echo "Pull request not found"
          fi
        
            
      
