name: semgrep-sast-scan
on:
  pull_request:
  workflow_dispatch:
    
jobs:
  semgrep-full-scan:
    runs-on: ubuntu-latest
    permissions: 
     pull-requests: read
     contents: read

    steps:
      - name: Fetch target repository
        uses: actions/checkout@v2

      - name: Fetch Automation Scripts
        uses: actions/checkout@v2
        with:
          repository: Red-Assassin-Org/security-audit-automation
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: security-audit-automation

      - name: list directory structure
        run: echo {{ github.event.repository.name }}
        
      - name: Setup Semgrep
        run: |
          bash -i security-audit-automation/scripts/setup-semgrep.sh

      - name: Run built-in semgrep rules
        env: 
          PR_NUMBER: ${{ github.event.number }}
          GH_TOKEN: ${{ github.token }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: bash -i security-audit-automation/scripts/semgrep-built-in.sh
        
            
      
